import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-about',
  template: `
    <div class="center">
        <header class="w3-header w3-grey ">
            <h1>About</h1>
        </header>
        <p class="p-spaced-2">I'm probably a little different from your typical candidate.</p>
        <p class="p-spaced-2">I started as a freelance writer and marketing communications consultant. I've found my way through the corporate world, including a Fortune 500 telecom. More recently, I worked at a nonprofit and a startup and now in the public sector in the County Manager's Office in Johnson County, Kansas.</p>
        <p class="p-spaced-2">My work on Accessibility is the perfect culmination of all the places I've been and the jobs I've done, in particular over the last several years. I'm obsessed with making sure that the digital content and services offered by the county I serve are accessible to everyone. It is about all the typical things you think about when you think of accessibility. It is WCAG and PDF/UA and Section 508. But in the year since I joined the County Manager's Office, it has also evolved into what I think of as <em>digital equity</em>.</p>
        <p class="p-spaced-2">Particularly as our communications have evolved during the pandemic, I have worked hard to make sure that every piece of critical content generated by any county department is accessible to people with disabilities and easy to use whether or not English is your first language.</p>
        <p class="p-spaced-2">For being the great tool for the dissemination of knowledge, the web has also marginalized people who are blind or deaf, those who have developmental disabilities, and people who are economically disadvantaged.</p>
        <p class="p-spaced-2">After working with some or all of those groups over the past 8 years or so, I found Accessibility to be a natural evolution of all the work that came before.</p>
        <p class="p-spaced-2">I've been working online for a long time. But my skills are fresh and I'm literally learning new things every day. Three years ago I had not taken apart a PDF and put it back together at the tag level. Or cloned a Git repository. Now I do those things every day.</p>
        <p class="p-spaced-2">And I'm looking for my next challenge.</p>
        <img class="img2" src="./assets/img/plane_pandemic_pic.jpg">
    </div>
  `,
  styles: [
  ]
})
export class AboutComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
